// <auto-generated />
using GestionViajesCaisabanda.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionViajesCaisabanda.Migrations
{
    [DbContext(typeof(ViajesContext))]
    partial class ViajesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestionViajesCaisabanda.Models.Destino", b =>
                {
                    b.Property<int>("destino_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("destino_id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("GestionViajesCaisabanda.Models.Turista", b =>
                {
                    b.Property<int>("turista_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("turista_id");

                    b.ToTable("Turistas");
                });
#pragma warning restore 612, 618
        }
    }
}
